### ISSUE TITLE
Backwards compatibility? Click anywhere to close?

### ISSUE THREAD

**Issue by CarlSinclair** [ammannbe/simple-aos#20]
## This is:

Question

## Specifications

  - Simple AOS version: Latest version of the OG repo
  - OS: AlmaLinux 9
  - Browser: All

Well I wanted to ask if it can be installed as a drop-in replacement for the old repo or if there would be any breaking migration instructions.

The only reason I care about any of this is because I'm interested in adding click anywhere to close functionality, so that users don't have to click the same hamburger menu trigger that turns into an X when open.

**Comment by ammannbe** [comment]
You shouldn't have any compatibility issues to the forked repo from [michalsnik/aos](https://github.com/michalsnik/aos).
At least not to the `michalsnik/aos:next` branch
